# Generated by Django 3.0.6 on 2020-05-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='qq',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
