# Generated by Django 3.0.7 on 2020-06-25 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysql', '0002_auto_20200625_0016'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='testmysql',
            table='apptest',
        ),
    ]
