# Generated by Django 3.0.7 on 2020-06-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20200625_0005'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMysql',
            fields=[
                ('uid', models.AutoField(db_column='uid', primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('rqtime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'apptest',
                'ordering': ['username'],
            },
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
