# Generated by Django 3.0.7 on 2020-07-26 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commentmeta',
            fields=[
                ('meta_id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增ID')),
                ('comment_id', models.BigIntegerField(verbose_name='评论ID')),
                ('meta_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='key')),
                ('meta_value', models.TextField(blank=True, null=True, verbose_name='value')),
            ],
            options={
                'db_table': 'commentmeta',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增ID')),
                ('comment_post_id', models.BigIntegerField(verbose_name='文章ID')),
                ('comment_author', models.TextField(verbose_name='作者')),
                ('comment_author_email', models.CharField(max_length=100, verbose_name='作者邮箱')),
                ('comment_author_url', models.CharField(max_length=200, verbose_name='作者链接')),
                ('comment_author_ip', models.CharField(max_length=100, verbose_name='作者IP')),
                ('comment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='评论时间')),
                ('comment_date_gmt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='评论时间GMT')),
                ('comment_content', models.TextField(verbose_name='评论内容')),
                ('comment_karma', models.IntegerField(blank=True, verbose_name='未使用')),
                ('comment_approved', models.CharField(max_length=20, verbose_name='评论状态(是否被批准)')),
                ('comment_agent', models.CharField(max_length=255, verbose_name='用户USERAGENT')),
                ('comment_type', models.CharField(max_length=20, verbose_name='评论状态(pingback引用/普通)')),
                ('comment_parent', models.BigIntegerField(blank=True, verbose_name='父ID(评论)')),
                ('user_id', models.BigIntegerField(verbose_name='用户ID')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('link_id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增ID')),
                ('link_url', models.CharField(max_length=255, verbose_name='链接URL')),
                ('link_name', models.CharField(max_length=255, verbose_name='连接标题')),
                ('link_image', models.CharField(max_length=255, verbose_name='链接图片')),
                ('link_target', models.CharField(max_length=25, verbose_name='图片打开方式')),
                ('link_description', models.CharField(max_length=255, verbose_name='链接描述')),
                ('link_visible', models.CharField(max_length=20, verbose_name='是否可见')),
                ('link_owner', models.BigIntegerField(verbose_name='添加者用户ID')),
                ('link_rating', models.IntegerField(verbose_name='评分等级')),
                ('link_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('link_rel', models.CharField(max_length=255, verbose_name='XFN关系')),
                ('link_notes', models.TextField(verbose_name='XFN注释')),
                ('link_rss', models.CharField(max_length=255, verbose_name='链接rss地址')),
            ],
            options={
                'db_table': 'links',
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增ID')),
                ('option_name', models.CharField(max_length=191, unique=True, verbose_name='key')),
                ('option_value', models.TextField(verbose_name='value')),
                ('autoload', models.CharField(max_length=20, verbose_name='是否在博客加载时自动载入')),
            ],
            options={
                'db_table': 'options',
            },
        ),
        migrations.CreateModel(
            name='Postmeta',
            fields=[
                ('meta_id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增ID')),
                ('post_id', models.BigIntegerField(verbose_name='文章ID')),
                ('meta_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='key')),
                ('meta_value', models.TextField(blank=True, null=True, verbose_name='value')),
            ],
            options={
                'db_table': 'postmeta',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增ID')),
                ('post_author', models.BigIntegerField(verbose_name='作者ID')),
                ('post_date', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('post_date_gmt', models.DateTimeField(auto_now_add=True, verbose_name='发布时间GMT')),
                ('post_content', models.TextField(verbose_name='正文')),
                ('post_title', models.TextField(verbose_name='标题')),
                ('post_excerpt', models.TextField(verbose_name='摘要')),
                ('post_status', models.CharField(max_length=20, verbose_name='文章状态')),
                ('comment_status', models.CharField(max_length=20, verbose_name='评论状态')),
                ('ping_status', models.CharField(max_length=20, verbose_name='ping状态')),
                ('post_password', models.CharField(max_length=255, verbose_name='文章密码')),
                ('post_name', models.CharField(max_length=200, verbose_name='文章缩略名')),
                ('to_ping', models.TextField(verbose_name='未使用')),
                ('pinged', models.TextField(verbose_name='已经ping过得链接')),
                ('post_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('post_modified_gmt', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间GMT')),
                ('post_content_filtered', models.TextField(verbose_name='未使用')),
                ('post_parent', models.BigIntegerField(verbose_name='父文章')),
                ('guid', models.CharField(max_length=255, verbose_name='GUID')),
                ('menu_order', models.IntegerField(verbose_name='排序ID')),
                ('post_type', models.CharField(max_length=20, verbose_name='文章类型')),
                ('post_mime_type', models.CharField(max_length=100, verbose_name='MIME类型')),
                ('comment_count', models.BigIntegerField(verbose_name='评论总数')),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Termmeta',
            fields=[
                ('meta_id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增ID')),
                ('term_id', models.BigIntegerField(verbose_name='分类ID')),
                ('meta_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='key')),
                ('meta_value', models.TextField(blank=True, null=True, verbose_name='value')),
            ],
            options={
                'db_table': 'termmeta',
            },
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('term_id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增ID')),
                ('name', models.CharField(max_length=200, verbose_name='分类名称')),
                ('slug', models.CharField(max_length=200, verbose_name='分类别名')),
                ('term_group', models.BigIntegerField(verbose_name='分类分组')),
            ],
            options={
                'db_table': 'terms',
            },
        ),
        migrations.CreateModel(
            name='Usermeta',
            fields=[
                ('umeta_id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增ID')),
                ('user_id', models.BigIntegerField(verbose_name='用户ID')),
                ('meta_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='key')),
                ('meta_value', models.TextField(blank=True, null=True, verbose_name='value')),
            ],
            options={
                'db_table': 'usermeta',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增ID')),
                ('user_login', models.CharField(max_length=60, verbose_name='用户名')),
                ('user_pass', models.CharField(max_length=255, verbose_name='密码')),
                ('user_nicename', models.CharField(max_length=50, verbose_name='昵称')),
                ('user_email', models.CharField(max_length=100, verbose_name='电子邮件')),
                ('user_url', models.CharField(max_length=100, verbose_name='网址')),
                ('user_registered', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('user_activation_key', models.CharField(max_length=255, null=True, verbose_name='激活码')),
                ('user_status', models.IntegerField(verbose_name='用户状态')),
                ('display_name', models.CharField(max_length=250, verbose_name='显示名称')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='TermTaxonomy',
            fields=[
                ('term_taxonomy_id', models.AutoField(primary_key=True, serialize=False, verbose_name='自增ID')),
                ('term_id', models.BigIntegerField(verbose_name='对应wp_terms表中的ID')),
                ('taxonomy', models.CharField(max_length=32, verbose_name='表示分类系统')),
                ('description', models.TextField(verbose_name='分类头像描述')),
                ('parent', models.BigIntegerField(verbose_name='父分类ID')),
                ('count', models.BigIntegerField(verbose_name='分类下内容数量')),
            ],
            options={
                'db_table': 'term_taxonomy',
                'unique_together': {('term_id', 'taxonomy')},
            },
        ),
        migrations.CreateModel(
            name='TermRelationships',
            fields=[
                ('object_id', models.AutoField(primary_key=True, serialize=False, verbose_name='对象ID')),
                ('term_taxonomy_id', models.BigIntegerField(verbose_name='分类ID')),
                ('term_order', models.IntegerField(verbose_name='分类排序')),
            ],
            options={
                'db_table': 'term_relationships',
                'unique_together': {('object_id', 'term_taxonomy_id')},
            },
        ),
    ]
